---
framework: golang
# blocklist:
#   - "/home/nucleus/repo/pkg/blocktestservice/setup_test.go##TestTestBlockListService_GetBlockListedTests"
#   - "/home/nucleus/repo/pkg/runner/docker/docker_test.go##TestDockerDestroyWithRunningWithAutoRemove"
#   - "/home/nucleus/repo/pkg/runner/docker/docker_test.go##TestDockerPullAlways"
#   - "/home/nucleus/repo/pkg/runner/docker/docker_test.go##TestDockerWaitCompletion"
#   - "/home/nucleus/repo/pkg/runner/docker/docker_test.go##TestDockerRun"
#   - "/home/nucleus/repo/pkg/runner/docker/docker_test.go##TestDockerPullNever"
#   - "/home/nucleus/repo/pkg/gitmanager/setup_test.go##TestClone"
  
preRun:
  command:
    - "go get -d ./..."
    - "go mod vendor"

postMerge:
 pattern:
    - ""
